[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first_multi'
sort_imports = true

[profile.default]
solc_version = '0.8.23'
libs = ['lib']
optimizer_runs = 10_000
extra_output = ["storageLayout", "metadata"]
extra_output_files = ["metadata"]
ast = true

[profile.optimized]
via_ir = true
out = 'out-via-ir'

[profile.test]
via_ir = true
out = 'out-via-ir'

[profile.docs]
src = 'src/interfaces/'

[profile.ci]
fuzz.runs = 256
verbosity = 2
show_progress = true
gas_reports = ["*"]

[fuzz]
runs = 1000

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }